LEARNING_RATE : 1e-3
LEARNING_SCHEDULER : CosineAnnealingLR
BATCH_SIZE : 32
NUM_EPOCHS : 200
LINEAR_PROBING: True
PROBING_EPOCHS : 50
PATIENCE : 200

IMAGE_SIZE : 336
HEATMAP: False

MODEL: ResNet50
PRETRAINED: True
LOSS: L1Loss