LEARNING_RATE : 1e-3
LEARNING_SCHEDULER : CosineAnnealingLR
BATCH_SIZE : 32
NUM_EPOCHS : 200
LINEAR_PROBING: False
PROBING_EPOCHS : 50
PATIENCE : 200

IMAGE_SIZE : 224

MODEL: ConvNeXtTiny
PRETRAINED: False
LOSS: L1Loss