LEARNING_RATE : 1e-3
LEARNING_SCHEDULER : CosineAnnealingLR
BATCH_SIZE : 64
NUM_EPOCHS : 80
LINEAR_PROBING: True
PROBING_EPOCHS : 30
PATIENCE : 50

IMAGE_SIZE : 224
HEATMAP: False

MODEL: ResNet50
PRETRAINED: True
LOSS: L1Loss